version: '3.8'

volumes:
  mongo_vol:

networks:
  python-flask-web:
    driver: bridge

services:
  mongodb: 
    image: mongo
    ports:
      - 27017:27017
    networks: 
     - python-flask-web
    volumes:
      - mongo_vol:/data/db
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
  
  python-flask: 
    image: rotten-potatoes-flask:${TAG}
    build: 
      context: ./src
      dockerfile: ./Dockerfile
    ports: 
     - 5000:5000
    networks: 
     - python-flask-web
    environment: 
      MONGODB_DB: admin
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_USERNAME: mongouser
      MONGODB_PASSWORD: mongopwd
    depends_on:
      - mongodb

  mongo-exp: 
    depends_on: 
     - mongodb
    restart: unless-stopped
    image: mongo-express
    ports: 
     - 8081:8081
    networks: 
     - python-flask-web
    environment: 
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongouser
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopwd
      ME_CONFIG_MONGODB_URL: mongodb://mongouser:mongopwd@mongodb:27017/?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: mexpress
      ME_CONFIG_BASICAUTH_PASSWORD: mexpress