apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mongodb-pvc
spec: 
  storageClassName: manual
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: host-storage
spec: 
  storageClassName: manual
  capacity: 
    storage: 1Gi
  accessModes: 
    - ReadWriteOnce
  hostPath: 
    path: "/mnt/k8s/volumes/mongodb"
    type: DirectoryOrCreate