apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mongodb
spec: 
  selector: 
    matchLabels: 
      app: mongodb
  template: 
    metadata: 
      labels: 
        app: mongodb
    spec: 
      containers: 
        - name: mongodb
          image: mongo:6.0
          env: 
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongouser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongopwd
          ports: 
            - containerPort: 27017
          volumeMounts: 
            - mountPath: /data/db
              name: mongodb-vol
      volumes: 
        - name: mongodb-vol
          persistentVolumeClaim: 
            claimName: mongodb-pvc
---

apiVersion: v1
kind: Service
metadata: 
  name: mongodb-service
spec: 
  selector: 
    app: mongodb
  ports: 
    - port: 27017



---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mongo-interface
spec: 
  selector: 
    matchLabels: 
      app: mongo-exp
  template: 
    metadata: 
      labels: 
        app: mongo-exp
    spec: 
      containers: 
        - name: mongo-exp
          image: mongo-express:1.0.0-alpha
          ports: 
            - containerPort: 8081
          env: 
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: mongouser
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: mongopwd
            - name: ME_CONFIG_MONGODB_URL
              value: mongodb://mongouser:mongopwd@mongodb-service:27017/?authSource=admin
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: mexpress
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: mexpress
              
---

apiVersion: v1
kind: Service
metadata: 
  name: service-interface
spec: 
  selector: 
    app: mongo-exp
  ports: 
    - port: 8081
      protocol: TCP
      targetPort: 8081
  type: LoadBalancer