apiVersion: apps/v1
kind: Deployment
metadata: 
  name: web-app
spec: 
  selector: 
    matchLabels: 
      app: web
  template: 
    metadata: 
      labels: 
        app: web
    spec: 
      containers: 
        - name: rotten-potatoes
          image: joaoinvernal/rotten-potatoes-reviewer:v2
          ports: 
            - containerPort: 5000
          env:
            - name: MONGODB_DB
              value: admin
            - name: MONGODB_HOST
              value: mongodb-service
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_USERNAME
              value: mongouser
            - name: MONGODB_PASSWORD
              value: mongopwd

---

apiVersion: v1
kind: Service
metadata: 
  name: web-service
spec: 
  selector: 
    app: web
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer